Update templates with latest ruleset changes
ppy/osu-templates pull request #24
Opened 2019-12-25 16:05 UTC by peppy

2020-01-30 14:08 UTC, frenzibyte requested changes

2020-01-30 14:08 UTC, iiSaLMaN commented on templates/ruleset-empty/osu.Game.Rulesets.EmptyFreeform/Beatmaps/EmptyFreeformBeatmapConverter.cs
> +        public override bool CanConvert() => true;
methods should reside after the constructor.

2020-01-30 14:08 UTC, iiSaLMaN commented on templates/ruleset-example/osu.Game.Rulesets.Pippidon/Beatmaps/PippidonBeatmapConverter.cs
> +        public override bool CanConvert() => Beatmap.HitObjects.All(h => h is IHasPosition);
ditto

2020-01-30 14:08 UTC, iiSaLMaN commented on templates/ruleset-scrolling-empty/osu.Game.Rulesets.EmptyScrolling/Beatmaps/EmptyScrollingBeatmapConverter.cs
> +        public override bool CanConvert() => true;
ditto

2020-01-31 08:05 UTC, peppy commented
Projects have been brought up-to-date with latest osu-side changes.

2020-01-31 08:09 UTC, frenzibyte approved these changes
Seems fine code-quality side.

2020-02-03 07:25 UTC, smoogipoo approved these changes

2020-02-03 07:25 UTC, merged